### ISSUE TITLE
How can we get chunk blob, is there any props around this ?

### ISSUE THREAD

**Issue by raj-reactgeeks** [0x006F/react-media-recorder#13] opened 2020-06-06 06:44 UTC
I want to get blob in a chunk, I have checked existing props I just found previewStream to get the current stream but I need a blob so that I can send it to server and store in real-time.

ondataavailable  method is available to get blob in a chunk, So can you please add chunk blob props support as well.

  mediaRecorder.ondataavailable = function (e: any) {
            console.log("blob =  ", e.data)
});

**Comment by wmik** [comment] 2020-06-27 05:48
Duplicate of #8

**Closed** 2020-06-29 18:45 UTC

**Comment by 0x006F** [comment] 2020-06-29 19:20
@raj-reactgeeks landed in `v1.2.1`
